# Generated by Django 2.0.1 on 2018-01-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=256)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('page_type', models.CharField(choices=[('ES', 'Essay'), ('MC', 'MultipleChoice'), ('TF', 'True-False'), ('DS', 'Discussion')], max_length=20)),
                ('text', models.CharField(max_length=512)),
                ('explanation', models.CharField(blank=True, max_length=512)),
                ('opinion', models.BooleanField(default=False)),
                ('reveal_answer', models.BooleanField()),
                ('visible', models.BooleanField(default=True)),
                ('tf_answer', models.BooleanField()),
                ('open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activity', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('essay', models.TextField(blank=True)),
                ('multi_choice', models.CharField(blank=True, max_length=1)),
                ('true_false', models.BooleanField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='closing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='index',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='overview',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='response',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Page'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Image'),
        ),
        migrations.AddField(
            model_name='choice',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('activity', 'index')},
        ),
    ]
