# Generated by Django 2.0.1 on 2018-02-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20180208_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['index'], 'verbose_name_plural': 'activities'},
        ),
    ]
