# Generated by Django 2.0.1 on 2018-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20180118_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('IN', 'Instructions'), ('ES', 'Essay'), ('MC', 'MultipleChoice'), ('TF', 'True-False'), ('DS', 'Discussion')], max_length=20),
        ),
    ]
