# Generated by Django 2.0.1 on 2018-01-19 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20180118_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Image'),
        ),
    ]
