# Generated by Django 2.0.1 on 2018-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20180211_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='discussion_type',
            field=models.CharField(blank=True, choices=[('OP', 'Open'), ('SA', 'Semi-Anonymous'), ('AN', 'Anonymous')], default='', max_length=20),
        ),
    ]
