# Generated by Django 2.0.1 on 2018-01-19 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20180118_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Image'),
        ),
    ]
