# Generated by Django 2.0.1 on 2018-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20180301_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('IN', 'Instructions'), ('ES', 'Essay'), ('MC', 'MultipleChoice'), ('TF', 'True-False'), ('DS', 'Discussion'), ('CH', 'Challenge')], max_length=20),
        ),
    ]
