# Generated by Django 2.0.1 on 2018-01-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='Read the Story', max_length=25),
            preserve_default=False,
        ),
    ]
