# Generated by Django 2.0.1 on 2018-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_page_timed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='correct',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='true_false',
            field=models.NullBooleanField(),
        ),
    ]
