# Generated by Django 2.0.1 on 2018-01-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20180125_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['index']},
        ),
    ]
