# Generated by Django 2.0.1 on 2018-01-31 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20180130_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['page', 'index']},
        ),
    ]
