# Generated by Django 2.0.1 on 2018-01-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20180130_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
