# Generated by Django 2.0.1 on 2018-01-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20180130_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='true_false.html',
            field=models.BooleanField(default=False),
        ),
    ]
