# Generated by Django 2.0.1 on 2018-01-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20180130_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='multi_choice',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
