# Generated by Django 2.0.1 on 2018-02-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20180130_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='open',
        ),
        migrations.AddField(
            model_name='page',
            name='discussion_type',
            field=models.CharField(choices=[('OP', 'Open'), ('SA', 'Semi-Anonymous'), ('AN', 'Anonymous')], max_length=20, null=True),
        ),
    ]
