# Generated by Django 2.0.1 on 2018-02-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critique',
            name='url',
        ),
        migrations.AddField(
            model_name='critique',
            name='path',
            field=models.CharField(default='/activity/welcome/', max_length=100),
            preserve_default=False,
        ),
    ]
