# Generated by Django 2.0.1 on 2018-02-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20180208_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'verbose_name_plural': 'help categories'},
        ),
        migrations.RenameField(
            model_name='helppage',
            old_name='page_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='helppage',
            old_name='page',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='helppage',
            unique_together={('category', 'number')},
        ),
    ]
